In [1]:
# Comprehensions

keyfile='Datafiles/key.txt'
key=dictionaryKeyFile(keyfile)
#evenkeys={item for item in key.items() if items[item]%2==0}
evenkeys={item for item in key}
evenkeys

NameError: name 'dictionaryKeyFile' is not defined

## Numpy Library

- It is an N-Dementional 
- It is used for Process N-Dimentional Array

In [7]:
import numpy as np
li=[1,3,5,'a','r','s']

a=np.array(li)
a
type(a)

b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
rn=np.random.randint(0,100,size=10)

rn

array([15, 26, 40, 92, 87, 22, 49, 30, 71, 43])

In [23]:
n3=np.random.randint(0,10,size=(2,4,2))
n3

array([[[9, 0],
        [2, 7],
        [6, 5],
        [7, 3]],

       [[7, 2],
        [7, 7],
        [1, 7],
        [3, 8]]])

In [17]:
n3=np.random.randint(0,10,size=(2,4,2,3))
n3
n3[1][1][1][1]

array([[[[8, 9, 7],
         [8, 0, 1]],

        [[4, 1, 1],
         [2, 1, 4]],

        [[0, 4, 1],
         [1, 8, 8]],

        [[0, 8, 8],
         [8, 2, 0]]],


       [[[1, 0, 5],
         [7, 8, 5]],

        [[8, 9, 4],
         [4, 1, 0]],

        [[5, 5, 8],
         [3, 6, 1]],

        [[7, 6, 3],
         [2, 0, 4]]]])

In [18]:
rn

array([15, 26, 40, 92, 87, 22, 49, 30, 71, 43])

In [19]:
rn[::3]

array([15, 92, 49, 43])

In [20]:
rn[::-1]

array([43, 71, 30, 49, 22, 87, 92, 40, 26, 15])

In [21]:
rn[1::2]

array([26, 92, 22, 30, 43])

In [25]:
n3[:1,:2]

array([[[9, 0],
        [2, 7]]])